// Talent Reconnect Agent - Infrastructure
// Deploys: AI Foundry + Project + Models, Azure AI Search, Application Insights

targetScope = 'subscription'

// ============================================================================
// Parameters
// ============================================================================

@description('Base name for all resources (will be used as prefix)')
param baseName string = 'talentreconnect'

@description('Azure region for deployment')
param location string = 'eastus2'

@description('Environment (dev, staging, prod)')
@allowed(['dev', 'staging', 'prod'])
param environment string = 'dev'

@description('Deploy Application Insights for observability')
param deployAppInsights bool = true

@description('Azure AI Search SKU')
@allowed(['basic', 'standard', 'standard2', 'standard3'])
param searchSku string = 'standard'

// ============================================================================
// Variables
// ============================================================================

var resourceGroupName = 'rg-${baseName}-${environment}'
var uniqueSuffix = uniqueString(subscription().subscriptionId, baseName, environment)
var aiFoundryName = 'ai-${baseName}-${uniqueSuffix}'
var aiProjectName = '${aiFoundryName}-proj'
var searchServiceName = 'search-${baseName}-${uniqueSuffix}'
var logAnalyticsName = 'log-${baseName}-${uniqueSuffix}'
var appInsightsName = 'appi-${baseName}-${uniqueSuffix}'

var tags = {
  project: 'talent-reconnect-agent'
  environment: environment
  deployedBy: 'bicep'
}

// ============================================================================
// Resource Group
// ============================================================================

resource rg 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

// ============================================================================
// Modules
// ============================================================================

module aiFoundry 'modules/ai-foundry.bicep' = {
  scope: rg
  params: {
    aiFoundryName: aiFoundryName
    aiProjectName: aiProjectName
    location: location
    tags: tags
  }
}

module search 'modules/search.bicep' = {
  scope: rg
  params: {
    searchServiceName: searchServiceName
    location: location
    sku: searchSku
    tags: tags
  }
}

module observability 'modules/observability.bicep' = if (deployAppInsights) {
  scope: rg
  params: {
    logAnalyticsName: logAnalyticsName
    appInsightsName: appInsightsName
    location: location
    tags: tags
  }
}

// ============================================================================
// Outputs
// ============================================================================

output resourceGroupName string = rg.name

// AI Foundry outputs
output aiFoundryEndpoint string = aiFoundry.outputs.endpoint
output aiFoundryName string = aiFoundry.outputs.name
output aiProjectName string = aiFoundry.outputs.projectName

// Search outputs
output searchEndpoint string = search.outputs.endpoint
output searchName string = search.outputs.name

// Observability outputs (conditional)
output appInsightsConnectionString string = observability.?outputs.?connectionString ?? ''
output appInsightsName string = observability.?outputs.?name ?? ''

// Environment file helper
output envFileContent string = '''
# Generated by Bicep deployment
# Copy these values to your .env file

# Microsoft Foundry (Azure AI)
FOUNDRY_CHAT_ENDPOINT=${aiFoundryEndpoint}
FOUNDRY_MODEL_PRIMARY=gpt-4o-mini
FOUNDRY_MODEL_FAST=gpt-4o

# Azure AI Search
SEARCH_SERVICE_ENDPOINT=${searchEndpoint}
SEARCH_SERVICE_API_KEY=<get-from-portal-or-cli>
SEARCH_RESUME_INDEX=resumes
SEARCH_FEEDBACK_INDEX=feedback
AZURE_SEARCH_MODE=agentic
AZURE_FEEDBACK_MODE=agentic

# Application Insights (optional)
APPLICATIONINSIGHTS_CONNECTION_STRING=${appInsightsConnectionString}
'''
