"""
Resume Matcher Agent

Searches resumes and generates a comparison table.
"""

from agent_framework import ChatAgent
from agent_framework.openai import OpenAIChatClient
from tools import search_and_match_resumes


def create_resume_matcher_agent(chat_client: OpenAIChatClient) -> ChatAgent:
    """Create the resume matcher agent"""
    
    agent = ChatAgent(
        chat_client=chat_client,
        name="ResumeMatcherAgent",
        instructions="""You are a Resume Matching specialist who searches and evaluates candidates against job requirements.

When given a job description with requirements, use the search_and_match_resumes tool to:
1. Search the resume database
2. Match candidates against the requirements
3. Generate a detailed comparison table

Extract from the JD:
- Job title
- Required functional skills (list 5-6 key skills)
- Minimum years of experience
- Key screening questions
- Location preference

Call the tool with these parameters and return the generated table directly.

DO NOT modify or summarize the table - return it exactly as generated by the tool.""",
        tools=[search_and_match_resumes]
    )
    
    return agent
