#!/bin/bash
# Deploy Talent Reconnect infrastructure (public networking)
# Usage: bash deploy.sh [resource-group] [location]

set -e

RG_NAME="${1:-rg-talentreconnect}"
LOCATION="${2:-swedencentral}"

echo "🚀 Talent Reconnect - Public Infrastructure Deployment"
echo "   Resource Group: $RG_NAME"
echo "   Location: $LOCATION"
echo ""

# Create resource group
echo "1️⃣ Creating resource group..."
az group create --name "$RG_NAME" --location "$LOCATION" -o none
echo "   ✓ Resource group created"

# Deploy AI Foundry infrastructure
echo ""
echo "2️⃣ Deploying AI Foundry infrastructure..."
echo "   (AI Services, Project, Cosmos DB, AI Search, Storage)"
MAIN_OUTPUT=$(az deployment group create \
  --resource-group "$RG_NAME" \
  --template-file main.bicep \
  --parameters location="$LOCATION" aiServices=tragt \
  --query properties.outputs -o json)

PROJECT_ENDPOINT=$(echo "$MAIN_OUTPUT" | jq -r '.projectEndpoint.value')
SEARCH_ENDPOINT=$(echo "$MAIN_OUTPUT" | jq -r '.aiSearchEndpoint.value')
COSMOS_ENDPOINT=$(echo "$MAIN_OUTPUT" | jq -r '.cosmosEndpoint.value')

echo "   ✓ AI Foundry deployed"
echo "   Project: $PROJECT_ENDPOINT"

# Deploy App Hosting (Container Apps, APIM, App Insights)
echo ""
echo "3️⃣ Deploying App Hosting infrastructure..."
echo "   (Container Apps, API Management, Application Insights)"

# Get publisher email from git config or use default
PUBLISHER_EMAIL=$(git config user.email 2>/dev/null || echo "admin@talentreconnect.ai")

APP_OUTPUT=$(az deployment group create \
  --resource-group "$RG_NAME" \
  --template-file app-hosting.bicep \
  --parameters location="$LOCATION" \
               namePrefix=tragt \
               publisherEmail="$PUBLISHER_EMAIL" \
               aiFoundryEndpoint="$PROJECT_ENDPOINT" \
  --query properties.outputs -o json)

CONTAINER_APP_URL=$(echo "$APP_OUTPUT" | jq -r '.containerAppUrl.value')
ACR_LOGIN=$(echo "$APP_OUTPUT" | jq -r '.containerRegistryLoginServer.value')
APIM_URL=$(echo "$APP_OUTPUT" | jq -r '.apiManagementGatewayUrl.value')
APP_INSIGHTS=$(echo "$APP_OUTPUT" | jq -r '.appInsightsConnectionString.value')

echo "   ✓ App hosting deployed"
echo "   Container App: $CONTAINER_APP_URL"
echo "   Registry: $ACR_LOGIN"

# Generate .env file
echo ""
echo "4️⃣ Generating .env configuration..."
cat > ../.env.azure <<EOF
# Generated by deploy.sh on $(date)
# Talent Reconnect - Azure Configuration

# AI Foundry
PROJECT_ENDPOINT=$PROJECT_ENDPOINT

# Azure AI Search
AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
# Get API key from Azure Portal → AI Search → Keys

# Cosmos DB (session storage)
COSMOS_ENDPOINT=$COSMOS_ENDPOINT
COSMOS_DATABASE=talent-reconnect
COSMOS_CONTAINER=sessions

# Observability
APPLICATIONINSIGHTS_CONNECTION_STRING=$APP_INSIGHTS

# Container Apps
CONTAINER_APP_URL=$CONTAINER_APP_URL
ACR_LOGIN_SERVER=$ACR_LOGIN
APIM_GATEWAY_URL=$APIM_URL
EOF

echo "   ✓ Created ../.env.azure"

echo ""
echo "═══════════════════════════════════════════════════════"
echo "✅ Deployment Complete!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Endpoints:"
echo "  AI Foundry: $PROJECT_ENDPOINT"
echo "  AI Search:  $SEARCH_ENDPOINT"
echo "  Cosmos DB:  $COSMOS_ENDPOINT"
echo "  Container:  $CONTAINER_APP_URL"
echo "  APIM:       $APIM_URL"
echo ""
echo "Next steps:"
echo "  1. Copy .env.azure to .env: cp ../.env.azure ../.env"
echo "  2. Add AI Search API key to .env"
echo "  3. Build and push container image:"
echo "     az acr login --name ${ACR_LOGIN%%.*}"
echo "     docker build -t $ACR_LOGIN/talent-reconnect:latest .."
echo "     docker push $ACR_LOGIN/talent-reconnect:latest"
echo "  4. Update Container App with new image"
echo ""
